#
# spec file for package ollama-mcp
#
# Copyright (c) 2025 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#

Name:           ollama-mcp
Version:        0.1.0
Release:        1.vojtech
Summary:        MCP server exposing Ollama models as tools
License:        MIT
URL:            https://github.com/vojtechpavlik/ollama-mcp

# Source0 (Application) and Source1 (Vendor) are generated by the _service file
Source0:        %{name}-%{version}.tar.gz
Source1:        vendor.tar.gz

BuildRequires:  go >= 1.23
BuildRequires:  systemd-rpm-macros

%{?systemd_requires}

%description
ollama-mcp is an MCP (Model Context Protocol) server that exposes a local
Ollama language model as a tool over stdio. An MCP host can call the
generate tool to run prompts against the configured Ollama model.

%prep
%autosetup -p1 -a 1

%build
CGO_ENABLED=0 go build \
   -mod=vendor \
   -buildmode=pie \
   -ldflags="-w -s" \
   -o ollama-mcp

%install
install -D -m 0755 ollama-mcp %{buildroot}%{_bindir}/ollama-mcp
install -D -m 0644 ollama-mcp.service %{buildroot}%{_unitdir}/%{name}.service
install -D -m 0644 ollama-mcp.1 %{buildroot}%{_mandir}/man1/ollama-mcp.1
install -D -m 0644 config.yaml %{buildroot}%{_sysconfdir}/ollama-mcp/config.yaml

%check
go test ./...

%pre
%service_add_pre %{name}.service

%post
%service_add_post %{name}.service

%preun
%service_del_preun %{name}.service

%postun
%service_del_postun %{name}.service

%files
%license LICENSE
%doc README.md DESIGN.md
%{_bindir}/ollama-mcp
%{_unitdir}/%{name}.service
%{_mandir}/man1/ollama-mcp.1*
%dir %{_sysconfdir}/ollama-mcp
%config(noreplace) %{_sysconfdir}/ollama-mcp/config.yaml

%changelog
